#!/bin/bash

VERSION=0.1

DO_BUILD=n
DO_INSTALL=n
DO_UNINSTALL=n
DO_REMOVE=n
DO_PATCH=n
DO_CONFIGURE=n
DO_SELECT_PROFILE=y
DO_EXEC=n

BUDLIX_DIR=${HOME}/.budlix
PROFILE="default"
TARGET=""

usage() {
    echo "blx - build-your-nix tool v${VERSION}"
    echo
    echo "Build and install packages"
    echo
    echo "Usage: ${0} [options] [PKGNAME]"
    echo
    echo "Main commands:"
    echo "    -b,--build PACKAGE"
    echo "         build PACKAGE"
    echo ""
    echo "    -i,--install PACKAGE"
    echo "         install PACKAGE to sysroot"
    echo ""
    echo "    -u,--uninstall PACKAGE"
    echo "         un-install PACKAGE from sysroot"
    echo ""
    echo "    -r,--remove PACKAGE"
    echo "         remove PACKAGE from sysroot and build dir"
    echo ""
    echo "    -p,--profile PROFILE"
    echo "         select PROFILE (~/.budlix/profile/PROFILE) to"
    echo "         which perform the package command:"
    echo ""
    echo "         1) point ${BUDLIX_DIR}/profile/current to ${BUDLIX_DIR}/profile/dev"
    echo "             $ blx -p dev"
    echo ""
    echo "         2) only install package in selected profile (w/o changin current profile):"
    echo "             $ blx -p dev -i musl"
    echo ""
    echo "    -x,--exec"
    echo "        execute in PROFILE (current or specified via -p)"
    echo ""
    echo "Other options:"
    echo "    -o,--out PATH              output dir"
    echo "    --<pkgname>-srcdir=PATH    override source dir for the <pkgname>"
}

error() {
    echo "error: ${1}"
    exit 1
}

do_exec() {
    local sysroot=${OUTPUT_DIR}/sysroot

    make -C ${OUTPUT_DIR} dash-enable
    make -C ${OUTPUT_DIR} dash-install

    export SYSROOT=${sysroot}

    if [ -x ${OUTPUT_DIR}/profile.sh ]; then
        source ${OUTPUT_DIR}/profile.sh
    fi

    PATH=${sysroot}/usr/bin:${sysroot}/usr/sbin:${PATH} \
    MANPATH=${sysroot}/usr/man:${sysroot}/usr/share/man \
    TERMINFO=${sysroot}/usr/share/terminfo \
    SHELL=${sysroot}/usr/bin/sh \
    ${sysroot}/usr/bin/sh
}

do_make() {
    make -C ${PWD} O=${OUTPUT_DIR} $@
}

do_build() {
    local enable
    local build

    for t in $TARGET; do
        enable="${enable} ${t}-enable"
        build="${build} ${t}-rebuild"
    done

    do_make deps

    if [ -z "${enable}" ]; then
        do_make build
    else
        do_make $enable
        do_make $build
    fi
}

do_install() {
    local enable
    local install

    for t in $TARGET; do
        enable="${enable} ${t}-enable"
        install="${install} ${t}-reinstall"
    done

    do_make deps

    if [ -z "${enable}" ]; then
        do_make install
    else
        do_make $enable
        do_make $install
    fi
}

do_uninstall() {
    local uninstall

    for t in $TARGET; do
        uninstall="${uninstall} ${t}-uninstall"
    done

    if [ -z "${uninstall}" ]; then
        do_make uninstall
    else
        do_make $uninstall
    fi
}

do_remove() {
    local uninstall
    local disable
    local clean

    for t in $TARGET; do
        uninstall="${uninstall} ${t}-uninstall"
        clean="${clean} ${t}-dirclean"
        disable="${disable} ${t}-disable"
    done

    do_make $uninstall
    do_make $clean
    do_make $disable
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

while [ $# -gt 0 ]; do
	case $1 in
	    -b|--build)
		DO_BUILD=y
		;;
	    -i|--install)
		DO_INSTALL=y
		;;
	    -u|--uninstall)
		DO_UNINSTALL=y
		;;
	    -r|--remove)
		DO_REMOVE=y
		;;
	    -o|--out)
	       OUTPUT_DIR=$2 
	       shift
	       ;;

	    -p|--profile)
               DO_SELECT_PROFILE="y"
	       PROFILE=$2
	       shift
	       ;;

	    -x|--exec)
               DO_EXEC="y"
	       ;;

            --*-srcdir=*)
               pkgname="${1//-srcdir=*/}"
	       pkgname="${pkgname//--/}"
	       pkgname_upper="${pkgname//-/_}"
	       pkgname_upper="${pkgname^^}"
	       srcdir="${1//--$pkgname-srcdir=}"
	       eval "export ${pkgname_upper}_OVERRIDE_SRCDIR=\"$srcdir\""
               ;;
	    -h)
		usage
		exit
		;;
	    *)
		TARGET="$TARGET $1"
	esac

shift
done

if [ -z "${OUTPUT_DIR}" ]; then
    OUTPUT_DIR=${BUDLIX_DIR}/profile/${PROFILE}
fi

mkdir -p ${OUTPUT_DIR}

if [ ${DO_BUILD} == y ]; then
    if do_build; then
        exit 1
    fi
elif [ ${DO_INSTALL} == y ]; then
    if do_install; then
        exit 1
    fi
elif [ ${DO_UNINSTALL} == y ]; then
    if do_uninstall; then
        exit 1
    fi
elif [ ${DO_REMOVE} == y ]; then
    if do_remove; then
        exit 1
    fi
elif [ ${DO_EXEC} == y ]; then
    if do_exec; then
        exit 1
    fi
elif [ ${DO_SELECT_PROFILE} == y ]; then
    ln -nsf ${BUDLIX_DIR}/profile/${PROFILE} ${BUDLIX_DIR}/profile/current
else
    usage
    exit 1
fi
