#!/bin/sh

OUTPUT=${1}
SYSROOT=${OUTPUT}/sysroot

make -C ${OUTPUT} dash-enable
make -C ${OUTPUT} dash-install

PATH=${SYSROOT}/usr/bin:${SYSROOT}/usr/sbin:${PATH} \
	MANPATH=${SYSROOT}/usr/man:${SYSROOT}/usr/share/man \
	TERMINFO=${SYSROOT}/usr/share/terminfo \
	SHELL=${SYSROOT}/usr/bin/sh \
	${SYSROOT}/usr/bin/sh
