;; generated by unixstyle-install
#hash(
      (doc-dir . "@SYSROOT@/usr/share/doc/racket")
      (dll-dir . "@SYSROOT@/usr/lib")
      (lib-dir . "@SYSROOT@/usr/lib/racket")
      (share-dir . "@SYSROOT@/usr/share/racket")
      (include-dir . "@SYSROOT@/usr/include/racket")
      (bin-dir . "@SYSROOT@/usr/bin")
      (apps-dir . "@SYSROOT@/usr/share/applications")
      (man-dir . "@SYSROOT@/usr/share/man")
      (absolute-installation? . #t)
)
